const donneesProjets = [
    {
        titre: "Chroniques Dystopiques",
        technologie: "Unity 3D - C#",
        date: "2023 - Projet en Équipe (4)",
        lien: "index-projets/chroniques-dystopiques.html",
        id: "c-d",
        urlVignette: "url('../fichiers/images/CD.jpg');",
    },
    {
        titre: "Transit",
        technologie: "Unity 3D - C#",
        date: "2022",
        lien: "index-projets/transit.html",
        id: "transit",
        urlVignette: "url('../fichiers/images/transit.png');",
    },
    {
        titre: "Myosotis Memories",
        technologie: "Unity 2D - C# (Gamejam)",
        date: "2023 - Projet en Équipe (4)",
        lien: "index-projets/myositis.html",
        id: "MM",
        urlVignette: "url('../fichiers/images/myositis.png');",
    },
    {
        titre: "Chapeau Spree",
        technologie: "Unity 3D - C# (Multijoueur)",
        date: "2023 - Projet en Équipe (2)",
        lien: "index-projets/chapeau-spree.html",
        id: "chapeau",
        urlVignette: "url('../fichiers/images/chapeau.png');",
    },
    {
        titre: "L'aventure de la Moustache",
        technologie: "Unity 2D - C#",
        date: "2022",
        lien: "index-projets/moustache.html",
        id: "moustache",
        urlVignette: "url('../fichiers/images/moustache.png');",
        type: "Jeu Unity 2D",
        description: "",
    },
    {
        titre: "Bananarama",
        technologie: "JavaScript - HTML",
        date: "2021",
        lien: "index-projets/bananarama.html",
        id: "bananarama",
        urlVignette: "url('../fichiers/images/bananarama-couverture.png');",
    },
];